// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/goodbye/goodbye.proto

package goodbye

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type GoodbyeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodbyeRequest) Reset() {
	*x = GoodbyeRequest{}
	mi := &file_proto_goodbye_goodbye_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodbyeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodbyeRequest) ProtoMessage() {}

func (x *GoodbyeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goodbye_goodbye_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodbyeRequest.ProtoReflect.Descriptor instead.
func (*GoodbyeRequest) Descriptor() ([]byte, []int) {
	return file_proto_goodbye_goodbye_proto_rawDescGZIP(), []int{0}
}

func (x *GoodbyeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the goodbye message.
type GoodbyeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodbyeReply) Reset() {
	*x = GoodbyeReply{}
	mi := &file_proto_goodbye_goodbye_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodbyeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodbyeReply) ProtoMessage() {}

func (x *GoodbyeReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goodbye_goodbye_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodbyeReply.ProtoReflect.Descriptor instead.
func (*GoodbyeReply) Descriptor() ([]byte, []int) {
	return file_proto_goodbye_goodbye_proto_rawDescGZIP(), []int{1}
}

func (x *GoodbyeReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_goodbye_goodbye_proto protoreflect.FileDescriptor

const file_proto_goodbye_goodbye_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/goodbye/goodbye.proto\x12\fgrpc.goodbye\"$\n" +
	"\x0eGoodbyeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\fGoodbyeReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xd9\x02\n" +
	"\bFarewell\x12H\n" +
	"\n" +
	"SayGoodbye\x12\x1c.grpc.goodbye.GoodbyeRequest\x1a\x1a.grpc.goodbye.GoodbyeReply\"\x00\x12P\n" +
	"\x10SayGoodbyeStream\x12\x1c.grpc.goodbye.GoodbyeRequest\x1a\x1a.grpc.goodbye.GoodbyeReply\"\x000\x01\x12V\n" +
	"\x16SayGoodbyeClientStream\x12\x1c.grpc.goodbye.GoodbyeRequest\x1a\x1a.grpc.goodbye.GoodbyeReply\"\x00(\x01\x12Y\n" +
	"\x17SayGoodbyeBidirectional\x12\x1c.grpc.goodbye.GoodbyeRequest\x1a\x1a.grpc.goodbye.GoodbyeReply\"\x00(\x010\x01B\x1bZ\x19grpc-sample/proto/goodbyeb\x06proto3"

var (
	file_proto_goodbye_goodbye_proto_rawDescOnce sync.Once
	file_proto_goodbye_goodbye_proto_rawDescData []byte
)

func file_proto_goodbye_goodbye_proto_rawDescGZIP() []byte {
	file_proto_goodbye_goodbye_proto_rawDescOnce.Do(func() {
		file_proto_goodbye_goodbye_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_goodbye_goodbye_proto_rawDesc), len(file_proto_goodbye_goodbye_proto_rawDesc)))
	})
	return file_proto_goodbye_goodbye_proto_rawDescData
}

var file_proto_goodbye_goodbye_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_goodbye_goodbye_proto_goTypes = []any{
	(*GoodbyeRequest)(nil), // 0: grpc.goodbye.GoodbyeRequest
	(*GoodbyeReply)(nil),   // 1: grpc.goodbye.GoodbyeReply
}
var file_proto_goodbye_goodbye_proto_depIdxs = []int32{
	0, // 0: grpc.goodbye.Farewell.SayGoodbye:input_type -> grpc.goodbye.GoodbyeRequest
	0, // 1: grpc.goodbye.Farewell.SayGoodbyeStream:input_type -> grpc.goodbye.GoodbyeRequest
	0, // 2: grpc.goodbye.Farewell.SayGoodbyeClientStream:input_type -> grpc.goodbye.GoodbyeRequest
	0, // 3: grpc.goodbye.Farewell.SayGoodbyeBidirectional:input_type -> grpc.goodbye.GoodbyeRequest
	1, // 4: grpc.goodbye.Farewell.SayGoodbye:output_type -> grpc.goodbye.GoodbyeReply
	1, // 5: grpc.goodbye.Farewell.SayGoodbyeStream:output_type -> grpc.goodbye.GoodbyeReply
	1, // 6: grpc.goodbye.Farewell.SayGoodbyeClientStream:output_type -> grpc.goodbye.GoodbyeReply
	1, // 7: grpc.goodbye.Farewell.SayGoodbyeBidirectional:output_type -> grpc.goodbye.GoodbyeReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_goodbye_goodbye_proto_init() }
func file_proto_goodbye_goodbye_proto_init() {
	if File_proto_goodbye_goodbye_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_goodbye_goodbye_proto_rawDesc), len(file_proto_goodbye_goodbye_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_goodbye_goodbye_proto_goTypes,
		DependencyIndexes: file_proto_goodbye_goodbye_proto_depIdxs,
		MessageInfos:      file_proto_goodbye_goodbye_proto_msgTypes,
	}.Build()
	File_proto_goodbye_goodbye_proto = out.File
	file_proto_goodbye_goodbye_proto_goTypes = nil
	file_proto_goodbye_goodbye_proto_depIdxs = nil
}
